<!DOCTYPE html>












  


<html class="theme-next mist use-motion" lang="zh-CN">
<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<meta name="theme-color" content="#222">


























<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2">

<link rel="stylesheet" href="/css/main.css?v=7.0.0">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-cat.png?v=7.0.0">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-cat.png?v=7.0.0">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-cat.png?v=7.0.0">


  <link rel="mask-icon" href="/images/logo.svg?v=7.0.0" color="#222">







<script id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Mist',
    version: '7.0.0',
    sidebar: {"position":"left","display":"always","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false,"dimmer":false},
    fancybox: false,
    fastclick: false,
    lazyload: false,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>


  




  <meta name="description" content="主要包含raise,assert和try...except结构。">
<meta name="keywords" content="python语言特性">
<meta property="og:type" content="article">
<meta property="og:title" content="python中的异常处理">
<meta property="og:url" content="http://yoursite.com/2019/03/06/python中的异常处理/index.html">
<meta property="og:site_name" content="Jairo">
<meta property="og:description" content="主要包含raise,assert和try...except结构。">
<meta property="og:locale" content="zh-CN">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/intro.jpg">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/raise.jpg">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/assert.jpg">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/try_except.jpg">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/try_except_else.jpg">
<meta property="og:image" content="http://yoursite.com/2019/03/06/python中的异常处理/try_except_else_finally.jpg">
<meta property="og:updated_time" content="2019-03-07T13:29:31.170Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="python中的异常处理">
<meta name="twitter:description" content="主要包含raise,assert和try...except结构。">
<meta name="twitter:image" content="http://yoursite.com/2019/03/06/python中的异常处理/intro.jpg">






  <link rel="canonical" href="http://yoursite.com/2019/03/06/python中的异常处理/">



<script id="page.configurations">
  CONFIG.page = {
    sidebar: "",
  };
</script>

  <title>python中的异常处理 | Jairo</title>
  












  <noscript>
  <style>
  .use-motion .motion-element,
  .use-motion .brand,
  .use-motion .menu-item,
  .sidebar-inner,
  .use-motion .post-block,
  .use-motion .pagination,
  .use-motion .comments,
  .use-motion .post-header,
  .use-motion .post-body,
  .use-motion .collection-title { opacity: initial; }

  .use-motion .logo,
  .use-motion .site-title,
  .use-motion .site-subtitle {
    opacity: initial;
    top: initial;
  }

  .use-motion .logo-line-before i { left: initial; }
  .use-motion .logo-line-after i { right: initial; }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-CN">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Jairo</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
    
    
  </div>

  <div class="site-nav-toggle">
    <button aria-label="切换导航栏">
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>



<nav class="site-nav">
  
    <ul id="menu" class="menu">
      
        
        
        
          
          <li class="menu-item menu-item-home">

    
    
    
      
    

    

    <a href="/" rel="section"><i class="menu-item-icon fa fa-fw fa-home"></i> <br>首页</a>

  </li>
        
        
        
          
          <li class="menu-item menu-item-tags">

    
    
    
      
    

    

    <a href="/tags/" rel="section"><i class="menu-item-icon fa fa-fw fa-tags"></i> <br>标签</a>

  </li>
        
        
        
          
          <li class="menu-item menu-item-archives">

    
    
    
      
    

    

    <a href="/archives/" rel="section"><i class="menu-item-icon fa fa-fw fa-archive"></i> <br>归档</a>

  </li>

      
      
    </ul>
  

  
    

  

  
</nav>



  



</div>
    </header>

    


    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  

  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2019/03/06/python中的异常处理/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="Jairo">
      <meta itemprop="description" content>
      <meta itemprop="image" content="/images/avatar_square.png">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Jairo">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">python中的异常处理

              
            
          </h1>
        

        <div class="post-meta">
          <span class="post-time">

            
            
            

            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              

              
                
              

              <time title="创建时间：2019-03-06 20:09:14" itemprop="dateCreated datePublished" datetime="2019-03-06T20:09:14+08:00">2019-03-06</time>
            

            
              

              
                
                <span class="post-meta-divider">|</span>
                

                <span class="post-meta-item-icon">
                  <i class="fa fa-calendar-check-o"></i>
                </span>
                
                  <span class="post-meta-item-text">更新于</span>
                
                <time title="修改时间：2019-03-07 21:29:31" itemprop="dateModified" datetime="2019-03-07T21:29:31+08:00">2019-03-07</time>
              
            
          </span>

          

          
            
            
              
              <span class="post-comments-count">
                <span class="post-meta-divider">|</span>
                <span class="post-meta-item-icon">
                  <i class="fa fa-comment-o"></i>
                </span>
            
                <span class="post-meta-item-text">评论数：</span>
                <a href="/2019/03/06/python中的异常处理/#comments" itemprop="discussionUrl">
                  <span class="post-comments-count valine-comment-count" data-xid="/2019/03/06/python中的异常处理/" itemprop="commentCount"></span>
                </a>
              </span>
            
          

          
          
            <span id="/2019/03/06/python中的异常处理/" class="leancloud_visitors" data-flag-title="python中的异常处理">
              <span class="post-meta-divider">|</span>
              <span class="post-meta-item-icon">
                <i class="fa fa-eye"></i>
              </span>
              
                <span class="post-meta-item-text">阅读次数：</span>
              
                <span class="leancloud-visitors-count"></span>
            </span>
          

          
            <span class="post-meta-divider">|</span>
            <span class="post-meta-item-icon">
            <i class="fa fa-eye"></i>
             阅读次数： 
            <span class="busuanzi-value" id="busuanzi_value_page_pv"></span>
            </span>
          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <p>主要包含<code>raise</code>,<code>assert</code>和<code>try...except</code>结构。</p>
<a id="more"></a>
<p><a href="https://realpython.com/python-exceptions/" target="_blank" rel="noopener">参考链接</a></p>
<h1 id="概述"><a href="#概述" class="headerlink" title="概述"></a>概述</h1><p>本文总结python中的异常处理，包含以下内容：<br><img src="/2019/03/06/python中的异常处理/intro.jpg"></p>
<ul>
<li>Exceptions versus Syntax Errors</li>
<li>Raising an Exception</li>
<li>The AssertionError Exception</li>
<li>The try and except Block:Handling Exception</li>
<li>The else Clause</li>
<li>Cleaning Up After Using finally</li>
<li>Summing up</li>
</ul>
<h1 id="Exceptions-versus-Syntax-Errors"><a href="#Exceptions-versus-Syntax-Errors" class="headerlink" title="Exceptions versus Syntax Errors"></a>Exceptions versus Syntax Errors</h1><p>python脚本在运行的过程中，如果发生了错误就会终止运行，这种错误事件可能是：</p>
<ul>
<li>syntax error</li>
<li>exception</li>
</ul>
<p>那么这两种情况有什么区别呢？<code>syntax error</code>是当出现脚本书写上的语法错误时出现的，不涉及到计算结果或逻辑问题，有如下例子：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">print(<span class="number">0</span> / <span class="number">0</span>))</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">  File &quot;&lt;ipython-input-1-b786f13d5138&gt;&quot;, line 1</span><br><span class="line">    print(0 / 0))</span><br><span class="line">                ^</span><br><span class="line">SyntaxError: invalid syntax</span><br></pre></td></tr></table></figure>
<p>箭头所指的就是<code>syntax error</code>出现的地方，此例子中的语法错误是多了一个括号。修正这个错误再次运行：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">print(<span class="number">0</span> / <span class="number">0</span>)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">---------------------------------------------------------------------------</span><br><span class="line"></span><br><span class="line">ZeroDivisionError                         Traceback (most recent call last)</span><br><span class="line"></span><br><span class="line">&lt;ipython-input-2-b6c088d31521&gt; in &lt;module&gt;()</span><br><span class="line">----&gt; 1 print(0 / 0)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>
<p>此时所发生的就是<code>exception error</code>。在脚本中没有<code>syntax error</code>的前提下，才会触发<code>exception error</code>。提醒信息中会指出此<code>exception error</code>的具体类型。在此例中为<code>ZeroDivisionError</code>。<code>exception error</code>分为两类：</p>
<ul>
<li><a href="https://docs.python.org/3/library/exceptions.html" target="_blank" rel="noopener">build-in exceptions</a></li>
<li>self-defined exceptions</li>
</ul>
<h1 id="Raising-an-Exception"><a href="#Raising-an-Exception" class="headerlink" title="Raising an Exception"></a>Raising an Exception</h1><p>用户可以使用<code>raise</code>关键字，当满足所设定的条件时，主动触发异常。<img src="/2019/03/06/python中的异常处理/raise.jpg"><br><code>raise</code>的使用方式如下：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">x = <span class="number">10</span></span><br><span class="line"><span class="keyword">if</span> x &gt; <span class="number">5</span>:</span><br><span class="line">    <span class="keyword">raise</span> Exception(<span class="string">'x should not exceed 5.The value of x was: &#123;&#125;'</span>.format(x))</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">---------------------------------------------------------------------------</span><br><span class="line"></span><br><span class="line">Exception                                 Traceback (most recent call last)</span><br><span class="line"></span><br><span class="line">&lt;ipython-input-3-36d986f491c4&gt; in &lt;module&gt;()</span><br><span class="line">      1 x = 10</span><br><span class="line">      2 if x &gt; 5:</span><br><span class="line">----&gt; 3     raise Exception(&apos;x should not exceed 5.The value of x was: &#123;&#125;&apos;.format(x))</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Exception: x should not exceed 5.The value of x was: 10</span><br></pre></td></tr></table></figure>
<p>程序会在满足<code>raise</code>执行的条件后，执行<code>raise</code>语句。抛出一个错误，并打印出事先写好的错误信息。</p>
<h1 id="The-AssertionError-Exception"><a href="#The-AssertionError-Exception" class="headerlink" title="The AssertionError Exception"></a>The AssertionError Exception</h1><p>在python脚本的编写中，除了被动的等待程序报错，可以用<code>assert</code>关键字去主动的去探测一些错误，返回更多的与错误有关的信息。<a href="https://dbader.org/blog/python-assert-tutorial" target="_blank" rel="noopener">这里</a>是一篇介绍<code>assert</code>的博客。<code>assert</code>关键字后面会跟一个条件判断，当此条件为真时，程序继续正常执行；当条件为假时，则会抛出一个<code>AssertionError</code>。也就是说，<code>assert</code>语句是要保证脚本运行至此时，满足括号中的条件，如果不满足的话，则触发异常，终止程序。<img src="/2019/03/06/python中的异常处理/assert.jpg">见如下例子：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">x = <span class="number">6</span></span><br><span class="line"><span class="keyword">assert</span> (x == <span class="number">5</span>), <span class="string">"x should equal to 5."</span></span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">---------------------------------------------------------------------------</span><br><span class="line"></span><br><span class="line">AssertionError                            Traceback (most recent call last)</span><br><span class="line"></span><br><span class="line">&lt;ipython-input-4-5d942ae404fb&gt; in &lt;module&gt;()</span><br><span class="line">      1 x = 6</span><br><span class="line">----&gt; 2 assert (x == 5), &quot;x should equal to 5.&quot;</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">AssertionError: x should equal to 5.</span><br></pre></td></tr></table></figure>
<p>在这个例子中，程序在抛出一个<code>AssertionError</code>异常之后便终止了。那么如果还想再触发异常之后继续执行一些其他的指令呢？</p>
<h1 id="The-try-and-exception-Block-Handling-Exceptions"><a href="#The-try-and-exception-Block-Handling-Exceptions" class="headerlink" title="The try and exception Block:Handling Exceptions"></a>The try and exception Block:Handling Exceptions</h1><p>在python中，<code>try</code>和<code>except</code>结构用来捕捉异常情况，并做一些对应的处理。<code>try</code>之后的语句，如果存在异常，则会执行<code>except</code>之后的语句。<img src="/2019/03/06/python中的异常处理/try_except.jpg"></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">value_check</span><span class="params">(x)</span>:</span></span><br><span class="line">    <span class="keyword">assert</span> (x == <span class="number">5</span>), <span class="string">'x should equal to 5.'</span></span><br><span class="line">    x *= <span class="number">2</span></span><br><span class="line">    print(<span class="string">'Everything checks out.x = %d'</span> % x)</span><br></pre></td></tr></table></figure>
<p>上面这个函数中有一个<code>assert</code>语句，当<code>x != 5</code>时，则会抛出一个<code>AssertionError</code>异常。而<code>try</code>加<code>except</code>结构则可以在出现异常时，并不终止程序，进行一些其他操作。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">6</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'The value_check() function threw error.'</span>)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">The value_check() function threw error.</span><br></pre></td></tr></table></figure>
<p>这个例子中，<code>value_check()</code>函数在执行的过程中，出现了异常。但程序并没有<code>crash</code>，而是继续运行预先设置的语句，提示这个函数并没有成功执行。但是在此例之中，并不能知道<code>value_check()</code>函数在执行中出现的异常具体是什么类型的。若想要知道关于异常的更多的信息可以这样做：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">6</span>)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> error:</span><br><span class="line">    print(<span class="string">'The value_check() function threw error.'</span>)</span><br><span class="line">    print(error)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">The value_check() function threw error.</span><br><span class="line">x should equal to 5.</span><br></pre></td></tr></table></figure>
<p>打印出的第一条信息说明了<code>value_check()</code>函数在执行时抛出了异常。而第二条信息则代表该异常的类型为<code>AssertionError</code>异常，提示<code>value_check()</code>函数中，要求<code>x == 5</code>。下面再看一个例子，这个例子中出现的是<code>build-in</code>exception：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">        read_data = file.read()</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'Could not open file.log'</span>)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Could not open file.log</span><br></pre></td></tr></table></figure>
<p>因为并不存在<code>file.log</code>这个文件，所以就会执行<code>except</code>之后的语句。这里出现的异常是<code>FileNotFoundError</code>，这是一个<code>build-in</code>异常。更多的<code>build-in exception</code>见<a href="https://docs.python.org/3/library/exceptions.html" target="_blank" rel="noopener">Build-in Exceptions</a>。在官方文档中，是这样描述<code>FileNotFoundError</code>的：</p>
<blockquote>
<p>Raised when a file or directory is requested but doesn’t exist. Corresponds to errno ENOENT.</p>
</blockquote>
<p>若想捕获这一异常的具体类型，并打印出异常中包含的信息，可以像之前一样：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">        read_data = file.read()</span><br><span class="line"><span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> fnf_error:</span><br><span class="line">    print(fnf_error)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">[Errno 2] No such file or directory: &apos;file.log&apos;</span><br></pre></td></tr></table></figure>
<p>可以同时检测多个类型的异常。需要注意的是，<code>try</code>之后的语句，在触发了第一个异常之后，便会终止。</p>
<table><tr><td bgcolor="orange"><strong>Warning</strong>:若<code>except</code>之后接的是<code>Exception</code>，那么所有类型的异常都会触发这个代码块，也就没有体现出具体是哪一类异常。故这样做是不推荐的，更多的讨论见<a href="https://realpython.com/the-most-diabolical-python-antipattern/" target="_blank" rel="noopener">这里</a>。</td></tr></table>

<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">6</span>)</span><br><span class="line">    <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">        read_data = file.read()</span><br><span class="line"><span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> fnf_error:</span><br><span class="line">    print(fnf_error)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> ast_error:</span><br><span class="line">    print(<span class="string">'The value_check() function threw error.'</span>)</span><br><span class="line">    print(ast_error)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">The value_check() function threw error.</span><br><span class="line">x should equal to 5.</span><br></pre></td></tr></table></figure>
<p>在上面这段代码中，<code>try</code>之后的代码块当执行到<code>value_check()</code>函数时便抛出了异常，于是此代码块终止运行，并不会抛出之后的<code>FileNotFoundError</code>异常。那么当<code>value_check()</code>函数可以正常运行时，则是下面这种情况：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">5</span>)</span><br><span class="line">    <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">        read_data = file.read()</span><br><span class="line"><span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> fnf_error:</span><br><span class="line">    print(fnf_error)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> ast_error:</span><br><span class="line">    print(<span class="string">'The value_check() function threw error.'</span>)</span><br><span class="line">    print(ast_error)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Everything checks out.x = 10</span><br><span class="line">[Errno 2] No such file or directory: &apos;file.log&apos;</span><br></pre></td></tr></table></figure>
<p>小结一下：</p>
<ul>
<li><code>try</code>之后的代码块，当抛出第一个异常时便终止运行。</li>
<li><code>except</code>之后的代码块，是用户设定的在该异常发生时的处理方式。</li>
<li>可以用<code>except</code>关键词检测多种类型的异常，并分别做不同的后续处理。</li>
<li>直接用<code>except</code>关键词而不管具体是什么类型的异常是不推荐的。</li>
</ul>
<h1 id="The-else-Clause"><a href="#The-else-Clause" class="headerlink" title="The else Clause"></a>The else Clause</h1><p>还可以在<code>try</code>和<code>except</code>结构之后，再加<code>else</code>模块。<code>else</code>之后的内容在没有<code>try</code>代码块中没有异常抛出时，才会执行的。<img src="/2019/03/06/python中的异常处理/try_except_else.jpg">见如下例子：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">5</span>)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> error:</span><br><span class="line">    print(error)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    print(<span class="string">'Executing the else clause.'</span>)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Everything checks out.x = 10</span><br><span class="line">Executing the else clause.</span><br></pre></td></tr></table></figure>
<p>在<code>else</code>中当然也可以写入<code>try</code>加<code>except</code>结构：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">5</span>)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> error:</span><br><span class="line">    print(error)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">            read_data = file.read()</span><br><span class="line">    <span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> fnf_error:</span><br><span class="line">        print(fnf_error)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Everything checks out.x = 10</span><br><span class="line">[Errno 2] No such file or directory: &apos;file.log&apos;</span><br></pre></td></tr></table></figure>
<h1 id="Cleaning-Up-After-Using-finally"><a href="#Cleaning-Up-After-Using-finally" class="headerlink" title="Cleaning Up After Using finally"></a>Cleaning Up After Using finally</h1><p>在之上所介绍的<code>try</code>加<code>except</code>加<code>else</code>结构中，<code>except</code>和<code>else</code>都是有条件执行的。可以再加一个<code>finally</code>模块，来无条件的执行一些语句。<img src="/2019/03/06/python中的异常处理/try_except_else_finally.jpg">来看下面的例子：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    value_check(<span class="number">5</span>)</span><br><span class="line"><span class="keyword">except</span> AssertionError <span class="keyword">as</span> error:</span><br><span class="line">    print(error)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">with</span> open(<span class="string">'file.log'</span>) <span class="keyword">as</span> file:</span><br><span class="line">            read_data = file.read()</span><br><span class="line">    <span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> fnf_error:</span><br><span class="line">        print(fnf_error)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'Cleaning up, irrespective of any exceptions.'</span>)</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">Everything checks out.x = 10</span><br><span class="line">[Errno 2] No such file or directory: &apos;file.log&apos;</span><br><span class="line">Cleaning up, irrespective of any exceptions.</span><br></pre></td></tr></table></figure>
<p>不论<code>try</code>和<code>else</code>代码块中出现了什么异常，<code>finally</code>代码块都会被执行。</p>
<h1 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h1><p>在了解了<code>syntax error</code>和<code>exceptions</code>的区别之后，继续介绍了如何<code>raise</code>、<code>catch</code>和<code>handle</code>异常情况。</p>
<ul>
<li><code>raise</code>可以在满足某个条件时主动抛出异常。</li>
<li><code>assert</code>为了保证满足某个条件，若不满足则抛出异常。</li>
<li><code>try</code>代码块会被执行直到出现异常时终止。</li>
<li><code>except</code>可以捕捉<code>try</code>中出现的特性类型的异常，并做相对应的处理。</li>
<li><code>else</code>代码块会在<code>try</code>中没有出现异常时被执行。</li>
<li><code>finally</code>代码块不论之前结构中是否出现异常，都会被执行。</li>
</ul>

      
    </div>

    

    
    
    

    

    
      
    
    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/python语言特性/" rel="tag"># python语言特性</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2019/03/05/博客优化日志/" rel="next" title="博客优化日志">
                <i class="fa fa-chevron-left"></i> 博客优化日志
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2019/03/08/3d人体姿态估计综述/" rel="prev" title="3d人体姿态估计综述">
                3d人体姿态估计综述 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>


  </div>


          </div>
          

  
    <div class="comments" id="comments">
    </div>

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <div class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <img class="site-author-image" itemprop="image" src="/images/avatar_square.png" alt="Jairo">
            
              <p class="site-author-name" itemprop="name">Jairo</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          
            <nav class="site-state motion-element">
              
                <div class="site-state-item site-state-posts">
                
                  <a href="/archives/">
                
                    <span class="site-state-item-count">6</span>
                    <span class="site-state-item-name">日志</span>
                  </a>
                </div>
              

              

              
                
                
                <div class="site-state-item site-state-tags">
                  <a href="/tags/index.html">
                    
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                    <span class="site-state-item-count">6</span>
                    <span class="site-state-item-name">标签</span>
                  </a>
                </div>
              
            </nav>
          

          

          
            <div class="links-of-author motion-element">
              
                <span class="links-of-author-item">
                  
                  
                    
                  
                  
                  <a href="https://www.zhihu.com/people/Ja1r0/activities" title="知乎 &rarr; https://www.zhihu.com/people/Ja1r0/activities" rel="noopener" target="_blank">知乎</a>
                </span>
              
                <span class="links-of-author-item">
                  
                  
                    
                  
                  
                  <a href="https://weibo.com/u/5601451342" title="微博 &rarr; https://weibo.com/u/5601451342" rel="noopener" target="_blank">微博</a>
                </span>
              
                <span class="links-of-author-item">
                  
                  
                    
                  
                  
                  <a href="mailto:jairoyang@qq.com" title="邮件 &rarr; mailto:jairoyang@qq.com" rel="noopener" target="_blank">邮件</a>
                </span>
              
            </div>
          

          

          
          

          
            
          
          

        </div>
      </div>

      
      <!--noindex-->
        <div class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
            
            
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#概述"><span class="nav-number">1.</span> <span class="nav-text">概述</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#Exceptions-versus-Syntax-Errors"><span class="nav-number">2.</span> <span class="nav-text">Exceptions versus Syntax Errors</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#Raising-an-Exception"><span class="nav-number">3.</span> <span class="nav-text">Raising an Exception</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#The-AssertionError-Exception"><span class="nav-number">4.</span> <span class="nav-text">The AssertionError Exception</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#The-try-and-exception-Block-Handling-Exceptions"><span class="nav-number">5.</span> <span class="nav-text">The try and exception Block:Handling Exceptions</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#The-else-Clause"><span class="nav-number">6.</span> <span class="nav-text">The else Clause</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#Cleaning-Up-After-Using-finally"><span class="nav-number">7.</span> <span class="nav-text">Cleaning Up After Using finally</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#总结"><span class="nav-number">8.</span> <span class="nav-text">总结</span></a></li></ol></div>
            

          </div>
        </div>
      <!--/noindex-->
      

      

    </div>
  </aside>
  


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2019</span>
  <span class="with-love" id="animate">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Jairo</span>

  

  
</div>


  <div class="powered-by">由 <a href="https://hexo.io" class="theme-link" rel="noopener" target="_blank">Hexo</a> 强力驱动 v3.8.0</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主题 – <a href="https://theme-next.org" class="theme-link" rel="noopener" target="_blank">NexT.Mist</a> v7.0.0</div>




        
<div class="busuanzi-count">
  <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>

  
    <span class="post-meta-item-icon">
      <i class="fa fa-user"></i>
    </span>
    <span class="site-uv" title="总访客量">
      <span class="busuanzi-value" id="busuanzi_value_site_uv"></span>
    </span>
  

  
    <span class="post-meta-divider">|</span>
  

  
    <span class="post-meta-item-icon">
      <i class="fa fa-eye"></i>
    </span>
    <span class="site-pv" title="总访问量">
      <span class="busuanzi-value" id="busuanzi_value_site_pv"></span>
    </span>
  
</div>









        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

    

    
  </div>

  

<script>
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>


























  
  <script src="/lib/jquery/index.js?v=2.1.3"></script>

  
  <script src="/lib/velocity/velocity.min.js?v=1.2.1"></script>

  
  <script src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>


  


  <script src="/js/src/utils.js?v=7.0.0"></script>

  <script src="/js/src/motion.js?v=7.0.0"></script>



  
  


  <script src="/js/src/schemes/muse.js?v=7.0.0"></script>




  
  <script src="/js/src/scrollspy.js?v=7.0.0"></script>
<script src="/js/src/post-details.js?v=7.0.0"></script>



  


  <script src="/js/src/bootstrap.js?v=7.0.0"></script>


  
  
  

<script src="//cdn1.lncld.net/static/js/3.11.1/av-min.js"></script>



<script src="//unpkg.com/valine/dist/Valine.min.js"></script>

<script>
  var GUEST = ['nick', 'mail', 'link'];
  var guest = 'nick,mail,link';
  guest = guest.split(',').filter(function(item) {
    return GUEST.indexOf(item) > -1;
  });
  new Valine({
    el: '#comments',
    verify: false,
    notify: false,
    appId: '9IIUquKAB8dC33rTPetpM2J0-gzGzoHsz',
    appKey: '2VD0aGQxj9ligzFy97AIn5h9',
    placeholder: '让我听到你的声音~',
    avatar: 'mm',
    meta: guest,
    pageSize: '10' || 10,
    visitor: false
  });
</script>




  


  




  
  
  <script>
    
    function addCount(Counter) {
      var $visitors = $('.leancloud_visitors');
      var url = $visitors.attr('id').trim();
      var title = $visitors.attr('data-flag-title').trim();

      Counter('get', '/classes/Counter', { where: JSON.stringify({ url }) })
        .done(function({ results }) {
          if (results.length > 0) {
            var counter = results[0];
            
            Counter('put', '/classes/Counter/' + counter.objectId, JSON.stringify({ time: { '__op': 'Increment', 'amount': 1 } }))
            
              .done(function() {
                var $element = $(document.getElementById(url));
                $element.find('.leancloud-visitors-count').text(counter.time + 1);
              })
            
              .fail(function ({ responseJSON }) {
                console.log('Failed to save Visitor num, with error message: ' + responseJSON.error);
              })
          } else {
            
              var $element = $(document.getElementById(url));
              $element.find('.leancloud-visitors-count').text('Counter not initialized! More info at console err msg.');
              console.error('ATTENTION! LeanCloud counter has security bug, see how to solve it here: https://github.com/theme-next/hexo-leancloud-counter-security. \n However, you can still use LeanCloud without security, by setting `security` option to `false`.');
            
          }
        })
        .fail(function ({ responseJSON }) {
          console.log('LeanCloud Counter Error: ' + responseJSON.code + ' ' + responseJSON.error);
        });
    }
    

    $(function() {
      $.get('https://app-router.leancloud.cn/2/route?appId=' + '9IIUquKAB8dC33rTPetpM2J0-gzGzoHsz')
        .done(function({ api_server }) {
          var Counter = function(method, url, data) {
            return $.ajax({
              method: method,
              url: 'https://' + api_server + '/1.1' + url,
              headers: {
                'X-LC-Id': '9IIUquKAB8dC33rTPetpM2J0-gzGzoHsz',
                'X-LC-Key': '2VD0aGQxj9ligzFy97AIn5h9',
                'Content-Type': 'application/json',
              },
              data: data
            });
          };
          
            addCount(Counter);
          
        });
    });
  </script>



  

  

  

  

  

  

  

  

  

  

  

  

<script src="/live2dw/lib/L2Dwidget.min.js?0c58a1486de42ac6cc1c59c7d98ae887"></script><script>L2Dwidget.init({"pluginRootPath":"live2dw/","pluginJsPath":"lib/","pluginModelPath":"assets/","tagMode":false,"debug":false,"model":{"jsonPath":"live2d-widget-model-wanko"},"display":{"position":"right","width":150,"height":300},"mobile":{"show":true},"log":false});</script></body>
</html>
<!-- 页面点击小红心 -->
<script type="text/javascript" src="/js/src/clicklove.js"></script>
